### ISSUE TITLE
Can a skip method be added to the Query class?

### ISSUE THREAD

**Issue by jaxtheking** [syedhussim/php-sapb1#10]
Hi,
I understand why the Query method `limit` couples `$top` with optionally `$skip`.
However, I need to cycle through Items by using the $skip variable returned by the previous request (@odata.nextLink) without $top.

Unless I missed something, could I ask for a `skip` method to be added please?
Thanks,
Luca

**Comment by syedhussim** [comment]
Hi Luca, 

Apologies for the delay, The issue with adding a skip method is that the response from the fetch method returns an array of data and not an object and so we cant call skip on the result. I could wrap the response data in a class and then add a skip method like the code below but it will break backward compatibility. 

`
$result = $query->fetchAll();
$result->skip();
`
The best way to handle this is to read the data from @odata.nextLink and extract the parameters then construct a new query. This is probably not what you want but unfortunately, I don't see any other way.

**Comment by jaxtheking** [comment]
Hi @syedhussim,
Thanks for your reply. You may have misunderstood what I meant - possibly due to my poor explanation.

I don't have a problem with extracting the skip parameter from @odata.nextLink; in fact I already do that.
The problem is I cannot apply it to subsequent queries because the `limit` method forces me to add a `top` parameter, which is not what I want.

To explain further, say I want to pull the second batch of Items with the `skip` parameter set to 100.
Using the `limit` method, I'd have to set a `top` param which messes my request as @odata.nextLink is not returned. E.g.:
`/Items?$top=100&$skip=100`.

What I need instead is to construct the following request:
`/Items?skip=100`.

From what I can see, the only way would be adding a `skip` method to the `Query` class, alongside the limit method:
```
/**
     * Specifies how many results to skip. 
     * Returns the current Query instance.
     */
    public function skip(int $skip) : Query{
        $this->query['skip'] = $skip;
        return $this;
    }
```

**Comment by syedhussim** [comment]
Hi Luca,

Thank you for the clarification. I've updated the source and added the skip method to the query class.

**Comment by jaxtheking** [comment]
Awesome, thank you!
Great library by the way, extremely concise and effective.
Luca
