### ISSUE TITLE
How to include .phar file inside Functions.php of Wordpress

### ISSUE THREAD

**Issue by gxb101** [syedhussim/php-sapb1#11]
Hi, thanks very much for this library,  but I am a bit stuck trying to make this work in conjunction with Wordpress and its functions.php file. I am trying to include your SAPb1.phar archive inside functions.php so I can pull some SAP data out, but when I do, the .phar file attempts to load all the other .php files Wordpress requires. Is there any workaround to this issue? Thanks in advance. This is what I see as an error msg:

failed to open stream: phar error: "xxxx/xxxx.php" is not a file in phar

**Comment by gxb101** [comment]
Hi, it sounds what's happening is what you're describing. Could I just explicitly list all the .php files found in /SAPb1 and its subfolder (/Filters) as includes? Anything else I would need to do? I've already attempted this approach, but the filters did not work for me as I kept getting "Fatal error: Uncaught Error: Class 'SAPb1\Filters\Equal' not found "  Any help you could provide would be appreciated. Thanks!

**Comment by syedhussim** [comment]
Hi, can you tell me how you're including the files?

**Comment by gxb101** [comment]
Hi, I believe I finally figured out the issue...didn't realize that the Filter class files had to be loaded in a specific order. I was just including them in alphabetical order (as they reside in the directory), however the Filter.php file must be loaded before any of the other filter class files are loaded or you'll get the error I was seeing. All good now. Appreciate your help.
