### ISSUE TITLE
Stock Transfer Example?

### ISSUE THREAD

**Issue by gxb101** [syedhussim/php-sapb1#13]
Hi, any chance you may have some PHP code examples for Stock Transfers? I saw your page mentioning them and the service layer, but I am mostly curious on the way the code would look using PHP. For example, I have the following, but there are syntax issues with it.:

$sap = new SAPClient($config, $session);
$InvTransfer = $sap->getService('StockTransfers');
$InvResults = $InvTransfer->create(
    "FromWarehouse": "WH-A",
    "StockTransferLines": [ 
        {
            "ItemCode": "12345",
            "Quantity": "1",
            "WarehouseCode" : "WH-B",
        }
    ]

Can this approach be used? Also, is there a way to also include a "From-Bin" Location in addition to a "To-Bin" Location when doing these movements? All your examples just showed the goods moving to a destination bin, not so much moving from different source bins. Thanks much for any assistance you're able to provide.

**Comment by Trim07** [comment]
Hi gxb101. 
You can follow the code bellow.

$sl = new SAPClient($config, $session);
$service = $sap->getService('StockTransfers');
$invTransfer = $service->create([
    'DocDate' => '2023-06-07',
    'TaxDate' => '2023-06-07',
    'FromWarehouse' => '01',
    'ToWarehouse' => '02',
    'Comments' => 'Xablau',
    'StockTransferLines' => [
        [
            'ItemCode' => '25300',
            'Quantity' => '1',
        ],
    ],
]);

The ServiceLayer follows the same logic as the DiAPI, in case of doubts with the parameters it is possible to consult the documentation.

**Comment by gxb101** [comment]
Trim07, thanks very much for the help - this works as expected! Can you let me know if we're able to tell SAP which Bin the SKUs should be transferred FROM rather than just leaving it at the warehouse level? I need to have my crew scan in a barcode representing a Source Bin in addition to the Destination Bin. If that's possible, what does the code look like? Thanks in advance.

**Comment by gxb101** [comment]
I was able to figure it out - code below in case anyone else finds this useful. This is code for doing a stock transfer between 2 bins in the SAME warehouse. You do not need to explicitly mention the from and to warehouses at the header level since you are providing the to and from bins later. Additionally, you will need to have two BinActionType entries (see below) : BinActionType = 1 (for the Destination Bin) and BinActionType =  2 (for the Source Bin).

```
`$service = $sap->getService('StockTransfers');
$invTransfer = $service->create([
					'DocDate' => '2023-06-07',
                                    //	'TaxDate' => '2023-06-07',
				   //	'FromWarehouse' => '17SH',
				   //	'ToWarehouse' => '17SH',
					'Comments' => 'Test',
					'StockTransferLines' => [
					[
						'ItemCode' => 'TS9800001001EA0EN07',
						'Quantity' => '5',
						'StockTransferLinesBinAllocations' => [
							[
							'BinAbsEntry' => '3749',
							'Quantity' => '5',
							'BinActionType' => '1',
							],
							[
							'BinAbsEntry' => '3804',
							'Quantity' => '5',
							'BinActionType' => '2',
							],
							       ],
                                          ],
										],
									]);`
```
