### ISSUE TITLE
Not able to set Odata.maxpagesize 

### ISSUE THREAD

**Issue by RanzigeMilch** [syedhussim/php-sapb1#2]
It is not possible to add additional Headers like "Prefer: odata.maxpagesize=0" to receive all results.

**Comment by camoralb** [comment]
> It is not possible to add additional Headers like "Prefer: odata.maxpagesize=0" to receive all results.

I'm gonna test it, and see if i could fix it and send it to the autor´s approbation.

**Comment by syedhussim** [comment]
I've added request headers to the service class. See readme for details.

**Comment by syedhussim** [comment]
Added headers, closing issue.
