### ISSUE TITLE
SAPClient class Fatal error calling query method

### ISSUE THREAD

**Issue by ruteshchaudhary** [syedhussim/php-sapb1#3]
Fatal error: Uncaught ArgumentCountError: Too few arguments to function SAPb1\Query::__construct(), 3 passed

**Comment by ruteshchaudhary** [comment]
I tried to change the method and generate new phar but the phar is failing to provid config class name space.

**Comment by syedhussim** [comment]
Hi ruteshchaudhary , can you provide some sample code, so I can reproduce the error.

**Comment by ruteshchaudhary** [comment]
$orders = $sap->query("Orders,Orders/DocumentLines,Items");

    $result = $orders->expand("expand=Orders($select=DocNum),Orders/DocumentLines($select=ItemCode),Items($select=ItemCode,ItemName,QuantityOrderedByCustomers)")
    ->where(new Equal("Orders/DocEntry","Orders/DocumentLines/DocEntry"))
    ->where(new Equal("Orders/DocumentLines/ItemCode","Items/ItemCode"))    
    ->findAll();

**Comment by syedhussim** [comment]
Hi ruteshchaudhary, I've fixed the code and committed the changes and generated a new phar file. However your code will still produce errors. Please use the Raw class as shown here. 

->where(new Raw("Orders/DocEntry eq Orders/DocumentLines/DocEntry"))

**Comment by ruteshchaudhary** [comment]
<br />
<font size='1'><table class='xdebug-error xe-notice' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Notice: Undefined variable: select in C:\wamp64\www\magnum_brands_api\cron\sapGetProductStrock.php on line <i>54</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0000</td><td bgcolor='#eeeeec' align='right'>363016</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\wamp64\www\magnum_brands_api\cron\sapGetProductStrock.php' bgcolor='#eeeeec'>...\sapGetProductStrock.php<b>:</b>0</td></tr>
</table></font>
<br />
<font size='1'><table class='xdebug-error xe-notice' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Notice: Undefined variable: select in C:\wamp64\www\magnum_brands_api\cron\sapGetProductStrock.php on line <i>54</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0000</td><td bgcolor='#eeeeec' align='right'>363016</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\wamp64\www\magnum_brands_api\cron\sapGetProductStrock.php' bgcolor='#eeeeec'>...\sapGetProductStrock.php<b>:</b>0</td></tr>
</table></font>
<br />
<font size='1'><table class='xdebug-error xe-notice' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Notice: Undefined variable: select in C:\wamp64\www\magnum_brands_api\cron\sapGetProductStrock.php on line <i>54</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0000</td><td bgcolor='#eeeeec' align='right'>363016</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\wamp64\www\magnum_brands_api\cron\sapGetProductStrock.php' bgcolor='#eeeeec'>...\sapGetProductStrock.php<b>:</b>0</td></tr>
</table></font>
<br />
<font size='1'><table class='xdebug-error xe-warning' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Warning: include(phar://C:\wamp64\www\magnum_brands_api\lib\php-sapb1-master\sapb1.phar/Raw.php): failed to open stream: phar error: &amp;quot;Raw.php&amp;quot; is not a file in phar &amp;quot;C:/wamp64/www/magnum_brands_api/lib/php-sapb1-master/sapb1.phar&amp;quot; in C:\wamp64\www\magnum_brands_api\lib\php-sapb1-master\sapb1.phar on line <i>5</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0000</td><td bgcolor='#eeeeec' align='right'>363016</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\wamp64\www\magnum_brands_api\cron\sapGetProductStrock.php' bgcolor='#eeeeec'>...\sapGetProductStrock.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0000</td><td bgcolor='#eeeeec' align='right'>386488</td><td bgcolor='#eeeeec'><a href='http://www.php.net/function.spl-autoload-call' target='_new'>spl_autoload_call</a>( <span>$class_name = </span><span>&#39;Raw&#39;</span> )</td><td title='C:\wamp64\www\magnum_brands_api\cron\sapGetProductStrock.php' bgcolor='#eeeeec'>...\sapGetProductStrock.php<b>:</b>55</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.0000</td><td bgcolor='#eeeeec' align='right'>386560</td><td bgcolor='#eeeeec'>{closure:C:\wamp64\www\magnum_brands_api\lib\php-sapb1-master\sapb1.phar:3-6}( <span>$class = </span><span>&#39;Raw&#39;</span> )</td><td title='C:\wamp64\www\magnum_brands_api\cron\sapGetProductStrock.php' bgcolor='#eeeeec'>...\sapGetProductStrock.php<b>:</b>55</td></tr>
</table></font>
<br />
<font size='1'><table class='xdebug-error xe-warning' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Warning: include(): Failed opening 'phar://C:\wamp64\www\magnum_brands_api\lib\php-sapb1-master\sapb1.phar/Raw.php' for inclusion (include_path='.;C:\php\pear') in C:\wamp64\www\magnum_brands_api\lib\php-sapb1-master\sapb1.phar on line <i>5</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0000</td><td bgcolor='#eeeeec' align='right'>363016</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\wamp64\www\magnum_brands_api\cron\sapGetProductStrock.php' bgcolor='#eeeeec'>...\sapGetProductStrock.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0000</td><td bgcolor='#eeeeec' align='right'>386488</td><td bgcolor='#eeeeec'><a href='http://www.php.net/function.spl-autoload-call' target='_new'>spl_autoload_call</a>( <span>$class_name = </span><span>&#39;Raw&#39;</span> )</td><td title='C:\wamp64\www\magnum_brands_api\cron\sapGetProductStrock.php' bgcolor='#eeeeec'>...\sapGetProductStrock.php<b>:</b>55</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.0000</td><td bgcolor='#eeeeec' align='right'>386560</td><td bgcolor='#eeeeec'>{closure:C:\wamp64\www\magnum_brands_api\lib\php-sapb1-master\sapb1.phar:3-6}( <span>$class = </span><span>&#39;Raw&#39;</span> )</td><td title='C:\wamp64\www\magnum_brands_api\cron\sapGetProductStrock.php' bgcolor='#eeeeec'>...\sapGetProductStrock.php<b>:</b>55</td></tr>
</table></font>
<br />
<font size='1'><table class='xdebug-error xe-uncaught-exception' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Fatal error: Uncaught Error: Class 'Raw' not found in C:\wamp64\www\magnum_brands_api\cron\sapGetProductStrock.php on line <i>55</i></th></tr>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Error: Class 'Raw' not found in C:\wamp64\www\magnum_brands_api\cron\sapGetProductStrock.php on line <i>55</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0000</td><td bgcolor='#eeeeec' align='right'>363016</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\wamp64\www\magnum_brands_api\cron\sapGetProductStrock.php' bgcolor='#eeeeec'>...\sapGetProductStrock.php<b>:</b>0</td></tr>
</table></font>

**Comment by ruteshchaudhary** [comment]
this is my new code. but it produces new error as per above

 $orders = $sap->query("Orders,Orders/DocumentLines,Items");

    $result = $orders->expand("expand=Orders($select=DocNum),Orders/DocumentLines($select=ItemCode),Items($select=ItemCode,ItemName,QuantityOrderedByCustomers)")
    ->where(new Raw("Orders/DocEntry eq Orders/DocumentLines/DocEntry"))
    ->where(new Raw("Orders/DocumentLines/ItemCode eq Items/ItemCode"))    
    ->findAll();

**Comment by syedhussim** [comment]
Yo need to include the Raw class from the Filters namespace. 

use SAPb1\Filters\Raw

**Comment by ruteshchaudhary** [comment]
thanks for your help, but i have suggestion if you can add some more exmaple in documentation for expanding crossjoin.
