### ISSUE TITLE
Support for services and PUT requests

### ISSUE THREAD

**Issue by Curadise** [syedhussim/php-sapb1#7]
I've been using this library for almost a year now. 
Since I'm working with the Picklists in SAP i was wondering if there could be support for
- Services. eg. the [PickListsService_UpdateReleasedAllocation], the normal POST operation does not seem to work?
- PUT requests. eg the [PUT][PickLists(id)]

According to the last one, the service Layer describes:
_PickList is a very special object. The exposed properties are not enough for Service Layer to finish a patch operation with 'PickListsLines'. In this way, use 'put' instead._

**Comment by syedhussim** [comment]
Hi Curadise, I'm sorry for the very late reply, were you able to resolve this, if not, can you tell me if you're updating the picklist.

**Comment by Curadise** [comment]
No problem, no unfortunately I was not, for now I'm working with a cURL workaround

I have an example for the first one:
`$OrdersService = $sap->getService("OrdersService_Preview");`
`$result = $OrdersService->create(["Document" => ["CardCode" => "C1122", "DocDueDate" => "2022-03-31", "DocumentLines" => [["ItemCode" => "110001", "Quantity" => "10"]]]]);`
Normally (via postman) this gives you back a full preview of the order
Can it be related to the http-resonse? The service returns 200 OK, a normal post (create) returns 201 Created

The second one I'm trying to update the Picklist yes, in stead of a patch, a put is required here

**Comment by syedhussim** [comment]
Hi Curadise

I've provided a fix for both issues. For the create, the service was returning http code 200 and not 201 and as a result it was throwing an exception. I've also added a second boolean argument to the create method. Setting this argument to true will return the response object, which includes http status code/headers and body.

`create(array $data, $returnResponse = false)`

Ive also added an argument in the update method, which you can use to change the http method.

` update($id, array $data, $returnResponse = false, $method = 'PATCH')`

Hope this helps.

**Comment by Curadise** [comment]
Hi Syed, thank you for the quick adjustments. 
Services work like a charm now 👍 
I will test the PUT request later
